/*
 * Pulze.ai API
 * At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.LLMModelPolicies;
import com.konfigthis.client.model.LLMModelWeights;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for App
 */
public class AppTest {
    private final App model = new App();

    /**
     * Model tests for App
     */
    @Test
    public void testApp() {
        // TODO: test App
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'addedOn'
     */
    @Test
    public void addedOnTest() {
        // TODO: test addedOn
    }

    /**
     * Test the property 'auth0Id'
     */
    @Test
    public void auth0IdTest() {
        // TODO: test auth0Id
    }

    /**
     * Test the property 'hashedKey'
     */
    @Test
    public void hashedKeyTest() {
        // TODO: test hashedKey
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'keyEnd'
     */
    @Test
    public void keyEndTest() {
        // TODO: test keyEnd
    }

    /**
     * Test the property 'modifiedOn'
     */
    @Test
    public void modifiedOnTest() {
        // TODO: test modifiedOn
    }

    /**
     * Test the property 'orgId'
     */
    @Test
    public void orgIdTest() {
        // TODO: test orgId
    }

    /**
     * Test the property 'policies'
     */
    @Test
    public void policiesTest() {
        // TODO: test policies
    }

    /**
     * Test the property 'promptId'
     */
    @Test
    public void promptIdTest() {
        // TODO: test promptId
    }

    /**
     * Test the property 'rateLimit'
     */
    @Test
    public void rateLimitTest() {
        // TODO: test rateLimit
    }

    /**
     * Test the property 'settings'
     */
    @Test
    public void settingsTest() {
        // TODO: test settings
    }

    /**
     * Test the property 'weights'
     */
    @Test
    public void weightsTest() {
        // TODO: test weights
    }

}
