/*
 * Pulze.ai API
 * At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OrgUsage;
import com.konfigthis.client.model.SubscriptionPaused;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Org
 */
public class OrgTest {
    private final Org model = new Org();

    /**
     * Model tests for Org
     */
    @Test
    public void testOrg() {
        // TODO: test Org
    }

    /**
     * Test the property 'addedOn'
     */
    @Test
    public void addedOnTest() {
        // TODO: test addedOn
    }

    /**
     * Test the property 'address1'
     */
    @Test
    public void address1Test() {
        // TODO: test address1
    }

    /**
     * Test the property 'address2'
     */
    @Test
    public void address2Test() {
        // TODO: test address2
    }

    /**
     * Test the property 'addressCity'
     */
    @Test
    public void addressCityTest() {
        // TODO: test addressCity
    }

    /**
     * Test the property 'addressCountry'
     */
    @Test
    public void addressCountryTest() {
        // TODO: test addressCountry
    }

    /**
     * Test the property 'addressState'
     */
    @Test
    public void addressStateTest() {
        // TODO: test addressState
    }

    /**
     * Test the property 'addressZip'
     */
    @Test
    public void addressZipTest() {
        // TODO: test addressZip
    }

    /**
     * Test the property 'billingEmail'
     */
    @Test
    public void billingEmailTest() {
        // TODO: test billingEmail
    }

    /**
     * Test the property 'creditBalance'
     */
    @Test
    public void creditBalanceTest() {
        // TODO: test creditBalance
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'freeBalance'
     */
    @Test
    public void freeBalanceTest() {
        // TODO: test freeBalance
    }

    /**
     * Test the property 'hubspotId'
     */
    @Test
    public void hubspotIdTest() {
        // TODO: test hubspotId
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'isPersonal'
     */
    @Test
    public void isPersonalTest() {
        // TODO: test isPersonal
    }

    /**
     * Test the property 'lastInvoiceDate'
     */
    @Test
    public void lastInvoiceDateTest() {
        // TODO: test lastInvoiceDate
    }

    /**
     * Test the property 'lokiEndpoint'
     */
    @Test
    public void lokiEndpointTest() {
        // TODO: test lokiEndpoint
    }

    /**
     * Test the property 'lokiId'
     */
    @Test
    public void lokiIdTest() {
        // TODO: test lokiId
    }

    /**
     * Test the property 'lokiToken'
     */
    @Test
    public void lokiTokenTest() {
        // TODO: test lokiToken
    }

    /**
     * Test the property 'modifiedOn'
     */
    @Test
    public void modifiedOnTest() {
        // TODO: test modifiedOn
    }

    /**
     * Test the property 'orgCreator'
     */
    @Test
    public void orgCreatorTest() {
        // TODO: test orgCreator
    }

    /**
     * Test the property 'orgDisplayName'
     */
    @Test
    public void orgDisplayNameTest() {
        // TODO: test orgDisplayName
    }

    /**
     * Test the property 'orgLogo'
     */
    @Test
    public void orgLogoTest() {
        // TODO: test orgLogo
    }

    /**
     * Test the property 'orgName'
     */
    @Test
    public void orgNameTest() {
        // TODO: test orgName
    }

    /**
     * Test the property 'orgStripeId'
     */
    @Test
    public void orgStripeIdTest() {
        // TODO: test orgStripeId
    }

    /**
     * Test the property 'pendingExpense'
     */
    @Test
    public void pendingExpenseTest() {
        // TODO: test pendingExpense
    }

    /**
     * Test the property 'periodEnd'
     */
    @Test
    public void periodEndTest() {
        // TODO: test periodEnd
    }

    /**
     * Test the property 'periodStart'
     */
    @Test
    public void periodStartTest() {
        // TODO: test periodStart
    }

    /**
     * Test the property 'promEndpoint'
     */
    @Test
    public void promEndpointTest() {
        // TODO: test promEndpoint
    }

    /**
     * Test the property 'promId'
     */
    @Test
    public void promIdTest() {
        // TODO: test promId
    }

    /**
     * Test the property 'promToken'
     */
    @Test
    public void promTokenTest() {
        // TODO: test promToken
    }

    /**
     * Test the property 'rateLimit'
     */
    @Test
    public void rateLimitTest() {
        // TODO: test rateLimit
    }

    /**
     * Test the property 'spendingLimitHard'
     */
    @Test
    public void spendingLimitHardTest() {
        // TODO: test spendingLimitHard
    }

    /**
     * Test the property 'spendingLimitSoft'
     */
    @Test
    public void spendingLimitSoftTest() {
        // TODO: test spendingLimitSoft
    }

    /**
     * Test the property 'subscriptionCycle'
     */
    @Test
    public void subscriptionCycleTest() {
        // TODO: test subscriptionCycle
    }

    /**
     * Test the property 'subscriptionPauseReason'
     */
    @Test
    public void subscriptionPauseReasonTest() {
        // TODO: test subscriptionPauseReason
    }

    /**
     * Test the property 'subscriptionPriceId'
     */
    @Test
    public void subscriptionPriceIdTest() {
        // TODO: test subscriptionPriceId
    }

    /**
     * Test the property 'subscriptionTier'
     */
    @Test
    public void subscriptionTierTest() {
        // TODO: test subscriptionTier
    }

    /**
     * Test the property 'trialEnd'
     */
    @Test
    public void trialEndTest() {
        // TODO: test trialEnd
    }

    /**
     * Test the property 'usage'
     */
    @Test
    public void usageTest() {
        // TODO: test usage
    }

}
