/*
 * Pulze.ai API
 * At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentDetailsBalance
 */
public class PaymentDetailsBalanceTest {
    private final PaymentDetailsBalance model = new PaymentDetailsBalance();

    /**
     * Model tests for PaymentDetailsBalance
     */
    @Test
    public void testPaymentDetailsBalance() {
        // TODO: test PaymentDetailsBalance
    }

    /**
     * Test the property 'balance'
     */
    @Test
    public void balanceTest() {
        // TODO: test balance
    }

    /**
     * Test the property 'billingZip'
     */
    @Test
    public void billingZipTest() {
        // TODO: test billingZip
    }

    /**
     * Test the property 'freeBalance'
     */
    @Test
    public void freeBalanceTest() {
        // TODO: test freeBalance
    }

    /**
     * Test the property 'lastSync'
     */
    @Test
    public void lastSyncTest() {
        // TODO: test lastSync
    }

    /**
     * Test the property 'pendingExpense'
     */
    @Test
    public void pendingExpenseTest() {
        // TODO: test pendingExpense
    }

    /**
     * Test the property 'spendingLimitHard'
     */
    @Test
    public void spendingLimitHardTest() {
        // TODO: test spendingLimitHard
    }

    /**
     * Test the property 'spendingLimitSoft'
     */
    @Test
    public void spendingLimitSoftTest() {
        // TODO: test spendingLimitSoft
    }

}
