/*
 * Pulze.ai API
 * At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SubscriptionSettings
 */
public class SubscriptionSettingsTest {
    private final SubscriptionSettings model = new SubscriptionSettings();

    /**
     * Model tests for SubscriptionSettings
     */
    @Test
    public void testSubscriptionSettings() {
        // TODO: test SubscriptionSettings
    }

    /**
     * Test the property 'customerSuccess'
     */
    @Test
    public void customerSuccessTest() {
        // TODO: test customerSuccess
    }

    /**
     * Test the property 'fineTuning'
     */
    @Test
    public void fineTuningTest() {
        // TODO: test fineTuning
    }

    /**
     * Test the property 'flowz'
     */
    @Test
    public void flowzTest() {
        // TODO: test flowz
    }

    /**
     * Test the property 'llmRouting'
     */
    @Test
    public void llmRoutingTest() {
        // TODO: test llmRouting
    }

    /**
     * Test the property 'maxApps'
     */
    @Test
    public void maxAppsTest() {
        // TODO: test maxApps
    }

    /**
     * Test the property 'maxAppsReadable'
     */
    @Test
    public void maxAppsReadableTest() {
        // TODO: test maxAppsReadable
    }

    /**
     * Test the property 'maxTokens'
     */
    @Test
    public void maxTokensTest() {
        // TODO: test maxTokens
    }

    /**
     * Test the property 'maxTokensReadable'
     */
    @Test
    public void maxTokensReadableTest() {
        // TODO: test maxTokensReadable
    }

    /**
     * Test the property 'monthlyPriceId'
     */
    @Test
    public void monthlyPriceIdTest() {
        // TODO: test monthlyPriceId
    }

    /**
     * Test the property 'monthlyPriceUsd'
     */
    @Test
    public void monthlyPriceUsdTest() {
        // TODO: test monthlyPriceUsd
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'personalizedLlmRouting'
     */
    @Test
    public void personalizedLlmRoutingTest() {
        // TODO: test personalizedLlmRouting
    }

    /**
     * Test the property 'promptModels'
     */
    @Test
    public void promptModelsTest() {
        // TODO: test promptModels
    }

    /**
     * Test the property 'prompts'
     */
    @Test
    public void promptsTest() {
        // TODO: test prompts
    }

    /**
     * Test the property 'supportLevel'
     */
    @Test
    public void supportLevelTest() {
        // TODO: test supportLevel
    }

    /**
     * Test the property 'supportLevelReadable'
     */
    @Test
    public void supportLevelReadableTest() {
        // TODO: test supportLevelReadable
    }

    /**
     * Test the property 'yearlyPriceId'
     */
    @Test
    public void yearlyPriceIdTest() {
        // TODO: test yearlyPriceId
    }

    /**
     * Test the property 'yearlyPriceUsd'
     */
    @Test
    public void yearlyPriceUsdTest() {
        // TODO: test yearlyPriceUsd
    }

}
