/*
 * Pulze.ai API
 * At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PulzeCompletionRequest;
import com.konfigthis.client.model.PulzeEngineResponse;
import com.konfigthis.client.model.RequestInDBBase;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * RequestNormalized
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class RequestNormalized {
  public static final String SERIALIZED_NAME_APP_ID = "app_id";
  @SerializedName(SERIALIZED_NAME_APP_ID)
  private UUID appId;

  public static final String SERIALIZED_NAME_AT = "at";
  @SerializedName(SERIALIZED_NAME_AT)
  private String at;

  public static final String SERIALIZED_NAME_CHILDREN = "children";
  @SerializedName(SERIALIZED_NAME_CHILDREN)
  private List<RequestInDBBase> children = null;

  public static final String SERIALIZED_NAME_COMPLETION_TOKENS = "completion_tokens";
  @SerializedName(SERIALIZED_NAME_COMPLETION_TOKENS)
  private Integer completionTokens;

  public static final String SERIALIZED_NAME_COMPLETION_TOKENS_COST = "completion_tokens_cost";
  @SerializedName(SERIALIZED_NAME_COMPLETION_TOKENS_COST)
  private Double completionTokensCost;

  public static final String SERIALIZED_NAME_COMPLETION_TOKENS_COST_SAVINGS = "completion_tokens_cost_savings";
  @SerializedName(SERIALIZED_NAME_COMPLETION_TOKENS_COST_SAVINGS)
  private Double completionTokensCostSavings;

  public static final String SERIALIZED_NAME_COSTS_INCURRED = "costs_incurred";
  @SerializedName(SERIALIZED_NAME_COSTS_INCURRED)
  private Boolean costsIncurred = true;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  private OffsetDateTime created;

  public static final String SERIALIZED_NAME_FEEDBACK = "feedback";
  @SerializedName(SERIALIZED_NAME_FEEDBACK)
  private String feedback = "";

  public static final String SERIALIZED_NAME_GOOD_ANSWER = "good_answer";
  @SerializedName(SERIALIZED_NAME_GOOD_ANSWER)
  private Boolean goodAnswer;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_LATENCY = "latency";
  @SerializedName(SERIALIZED_NAME_LATENCY)
  private Double latency = -1d;

  public static final String SERIALIZED_NAME_MODEL = "model";
  @SerializedName(SERIALIZED_NAME_MODEL)
  private String model;

  public static final String SERIALIZED_NAME_MODEL_ID = "model_id";
  @SerializedName(SERIALIZED_NAME_MODEL_ID)
  private UUID modelId;

  public static final String SERIALIZED_NAME_NAMESPACE = "namespace";
  @SerializedName(SERIALIZED_NAME_NAMESPACE)
  private String namespace;

  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  private String owner;

  public static final String SERIALIZED_NAME_PARENT = "parent";
  @SerializedName(SERIALIZED_NAME_PARENT)
  private RequestInDBBase parent;

  public static final String SERIALIZED_NAME_PARENT_ID = "parent_id";
  @SerializedName(SERIALIZED_NAME_PARENT_ID)
  private UUID parentId;

  public static final String SERIALIZED_NAME_PAYLOAD = "payload";
  @SerializedName(SERIALIZED_NAME_PAYLOAD)
  private PulzeCompletionRequest payload;

  /**
   * How much is logged? 1: everything, 2: mask request+response (but show log), 3: Not visible, not retrievable, no information stored.
   */
  @JsonAdapter(PrivacyLevelEnum.Adapter.class)
 public enum PrivacyLevelEnum {
    NUMBER_1(1),
    
    NUMBER_2(2),
    
    NUMBER_3(3);

    private Integer value;

    PrivacyLevelEnum(Integer value) {
      this.value = value;
    }

    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PrivacyLevelEnum fromValue(Integer value) {
      for (PrivacyLevelEnum b : PrivacyLevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PrivacyLevelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PrivacyLevelEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PrivacyLevelEnum read(final JsonReader jsonReader) throws IOException {
        Integer value =  jsonReader.nextInt();
        return PrivacyLevelEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_PRIVACY_LEVEL = "privacy_level";
  @SerializedName(SERIALIZED_NAME_PRIVACY_LEVEL)
  private PrivacyLevelEnum privacyLevel = PrivacyLevelEnum.NUMBER_1;

  public static final String SERIALIZED_NAME_PROMPT = "prompt";
  @SerializedName(SERIALIZED_NAME_PROMPT)
  private String prompt;

  public static final String SERIALIZED_NAME_PROMPT_TOKENS = "prompt_tokens";
  @SerializedName(SERIALIZED_NAME_PROMPT_TOKENS)
  private Integer promptTokens;

  public static final String SERIALIZED_NAME_PROMPT_TOKENS_COST = "prompt_tokens_cost";
  @SerializedName(SERIALIZED_NAME_PROMPT_TOKENS_COST)
  private Double promptTokensCost;

  public static final String SERIALIZED_NAME_PROMPT_TOKENS_COST_SAVINGS = "prompt_tokens_cost_savings";
  @SerializedName(SERIALIZED_NAME_PROMPT_TOKENS_COST_SAVINGS)
  private Double promptTokensCostSavings;

  public static final String SERIALIZED_NAME_PROVIDER = "provider";
  @SerializedName(SERIALIZED_NAME_PROVIDER)
  private String provider;

  /**
   * The type of request (text completion or chat) the user sends and expects back
   */
  @JsonAdapter(RequestTypeEnum.Adapter.class)
 public enum RequestTypeEnum {
    COMPLETIONS("completions"),
    
    CHAT_COMPLETIONS("chat_completions");

    private String value;

    RequestTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RequestTypeEnum fromValue(String value) {
      for (RequestTypeEnum b : RequestTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<RequestTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RequestTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RequestTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return RequestTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_REQUEST_TYPE = "request_type";
  @SerializedName(SERIALIZED_NAME_REQUEST_TYPE)
  private RequestTypeEnum requestType;

  public static final String SERIALIZED_NAME_RESPONSE = "response";
  @SerializedName(SERIALIZED_NAME_RESPONSE)
  private PulzeEngineResponse response;

  public static final String SERIALIZED_NAME_RESPONSE_TEXT = "response_text";
  @SerializedName(SERIALIZED_NAME_RESPONSE_TEXT)
  private String responseText;

  public static final String SERIALIZED_NAME_STATUS_CODE = "status_code";
  @SerializedName(SERIALIZED_NAME_STATUS_CODE)
  private Integer statusCode = -1;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  private Integer timestamp;

  public static final String SERIALIZED_NAME_TOTAL_TOKENS = "total_tokens";
  @SerializedName(SERIALIZED_NAME_TOTAL_TOKENS)
  private Integer totalTokens;

  public static final String SERIALIZED_NAME_TOTAL_TOKENS_COST = "total_tokens_cost";
  @SerializedName(SERIALIZED_NAME_TOTAL_TOKENS_COST)
  private Double totalTokensCost;

  public static final String SERIALIZED_NAME_TOTAL_TOKENS_COST_SAVINGS = "total_tokens_cost_savings";
  @SerializedName(SERIALIZED_NAME_TOTAL_TOKENS_COST_SAVINGS)
  private Double totalTokensCostSavings;

  public RequestNormalized() {
  }

  public RequestNormalized appId(UUID appId) {
    
    
    
    
    this.appId = appId;
    return this;
  }

   /**
   * The ID of the app that performed the request
   * @return appId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the app that performed the request")

  public UUID getAppId() {
    return appId;
  }


  public void setAppId(UUID appId) {
    
    
    
    this.appId = appId;
  }


  public RequestNormalized at(String at) {
    
    
    
    
    this.at = at;
    return this;
  }

   /**
   * Extra model settings inferred from namespace
   * @return at
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Extra model settings inferred from namespace")

  public String getAt() {
    return at;
  }


  public void setAt(String at) {
    
    
    
    this.at = at;
  }


  public RequestNormalized children(List<RequestInDBBase> children) {
    
    
    
    
    this.children = children;
    return this;
  }

  public RequestNormalized addChildrenItem(RequestInDBBase childrenItem) {
    if (this.children == null) {
      this.children = new ArrayList<>();
    }
    this.children.add(childrenItem);
    return this;
  }

   /**
   * The children of the Request. Will equal None unless you use eager loading in the query
   * @return children
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The children of the Request. Will equal None unless you use eager loading in the query")

  public List<RequestInDBBase> getChildren() {
    return children;
  }


  public void setChildren(List<RequestInDBBase> children) {
    
    
    
    this.children = children;
  }


  public RequestNormalized completionTokens(Integer completionTokens) {
    
    
    
    
    this.completionTokens = completionTokens;
    return this;
  }

   /**
   * Number of tokens the response used
   * @return completionTokens
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Number of tokens the response used")

  public Integer getCompletionTokens() {
    return completionTokens;
  }


  public void setCompletionTokens(Integer completionTokens) {
    
    
    
    this.completionTokens = completionTokens;
  }


  public RequestNormalized completionTokensCost(Double completionTokensCost) {
    
    
    
    
    this.completionTokensCost = completionTokensCost;
    return this;
  }

  public RequestNormalized completionTokensCost(Integer completionTokensCost) {
    
    
    
    
    this.completionTokensCost = completionTokensCost.doubleValue();
    return this;
  }

   /**
   * Cost (in $) of the response
   * @return completionTokensCost
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Cost (in $) of the response")

  public Double getCompletionTokensCost() {
    return completionTokensCost;
  }


  public void setCompletionTokensCost(Double completionTokensCost) {
    
    
    
    this.completionTokensCost = completionTokensCost;
  }


  public RequestNormalized completionTokensCostSavings(Double completionTokensCostSavings) {
    
    
    
    
    this.completionTokensCostSavings = completionTokensCostSavings;
    return this;
  }

  public RequestNormalized completionTokensCostSavings(Integer completionTokensCostSavings) {
    
    
    
    
    this.completionTokensCostSavings = completionTokensCostSavings.doubleValue();
    return this;
  }

   /**
   * Cost (in $) saved in the completion costs comparison to the benchmark model
   * @return completionTokensCostSavings
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Cost (in $) saved in the completion costs comparison to the benchmark model")

  public Double getCompletionTokensCostSavings() {
    return completionTokensCostSavings;
  }


  public void setCompletionTokensCostSavings(Double completionTokensCostSavings) {
    
    
    
    this.completionTokensCostSavings = completionTokensCostSavings;
  }


  public RequestNormalized costsIncurred(Boolean costsIncurred) {
    
    
    
    
    this.costsIncurred = costsIncurred;
    return this;
  }

   /**
   * When a request requires multiple intermediate calls, they are stored as &#39;no costs incurred&#39; -- that way we can store the costs, but don&#39;t charge the user
   * @return costsIncurred
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "When a request requires multiple intermediate calls, they are stored as 'no costs incurred' -- that way we can store the costs, but don't charge the user")

  public Boolean getCostsIncurred() {
    return costsIncurred;
  }


  public void setCostsIncurred(Boolean costsIncurred) {
    
    
    
    this.costsIncurred = costsIncurred;
  }


  public RequestNormalized created(OffsetDateTime created) {
    
    
    
    
    this.created = created;
    return this;
  }

   /**
   * When the request was performed
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "When the request was performed")

  public OffsetDateTime getCreated() {
    return created;
  }


  public void setCreated(OffsetDateTime created) {
    
    
    
    this.created = created;
  }


  public RequestNormalized feedback(String feedback) {
    
    
    
    
    this.feedback = feedback;
    return this;
  }

   /**
   * A free text providing more detailed feedback
   * @return feedback
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "", value = "A free text providing more detailed feedback")

  public String getFeedback() {
    return feedback;
  }


  public void setFeedback(String feedback) {
    
    
    
    this.feedback = feedback;
  }


  public RequestNormalized goodAnswer(Boolean goodAnswer) {
    
    
    
    
    this.goodAnswer = goodAnswer;
    return this;
  }

   /**
   * The rating for the request
   * @return goodAnswer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The rating for the request")

  public Boolean getGoodAnswer() {
    return goodAnswer;
  }


  public void setGoodAnswer(Boolean goodAnswer) {
    
    
    
    this.goodAnswer = goodAnswer;
  }


  public RequestNormalized id(UUID id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * ID of the request
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "ID of the request")

  public UUID getId() {
    return id;
  }


  public void setId(UUID id) {
    
    
    
    this.id = id;
  }


  public RequestNormalized latency(Double latency) {
    
    
    
    
    this.latency = latency;
    return this;
  }

  public RequestNormalized latency(Integer latency) {
    
    
    
    
    this.latency = latency.doubleValue();
    return this;
  }

   /**
   * Time it took for the LLM to respond
   * @return latency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "-1", value = "Time it took for the LLM to respond")

  public Double getLatency() {
    return latency;
  }


  public void setLatency(Double latency) {
    
    
    
    this.latency = latency;
  }


  public RequestNormalized model(String model) {
    
    
    
    
    this.model = model;
    return this;
  }

   /**
   * The name of the model. Can belong to many providers
   * @return model
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The name of the model. Can belong to many providers")

  public String getModel() {
    return model;
  }


  public void setModel(String model) {
    
    
    
    this.model = model;
  }


  public RequestNormalized modelId(UUID modelId) {
    
    
    
    
    this.modelId = modelId;
    return this;
  }

   /**
   * The ID of the model used
   * @return modelId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The ID of the model used")

  public UUID getModelId() {
    return modelId;
  }


  public void setModelId(UUID modelId) {
    
    
    
    this.modelId = modelId;
  }


  public RequestNormalized namespace(String namespace) {
    
    
    
    
    this.namespace = namespace;
    return this;
  }

   /**
   * The name of the provider&#39;s model which was used to answer the request
   * @return namespace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the provider's model which was used to answer the request")

  public String getNamespace() {
    return namespace;
  }


  public void setNamespace(String namespace) {
    
    
    
    this.namespace = namespace;
  }


  public RequestNormalized owner(String owner) {
    
    
    
    
    this.owner = owner;
    return this;
  }

   /**
   * The owner of the model. Sometimes, for a provider/model combination, many instances exist, trained on different data
   * @return owner
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The owner of the model. Sometimes, for a provider/model combination, many instances exist, trained on different data")

  public String getOwner() {
    return owner;
  }


  public void setOwner(String owner) {
    
    
    
    this.owner = owner;
  }


  public RequestNormalized parent(RequestInDBBase parent) {
    
    
    
    
    this.parent = parent;
    return this;
  }

   /**
   * The parent of the Request, if any. Requests which are part of a series of sub-requests (like multiple LLM calls, or RAG) will have the final, resulting Log as parent.
   * @return parent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The parent of the Request, if any. Requests which are part of a series of sub-requests (like multiple LLM calls, or RAG) will have the final, resulting Log as parent.")

  public RequestInDBBase getParent() {
    return parent;
  }


  public void setParent(RequestInDBBase parent) {
    
    
    
    this.parent = parent;
  }


  public RequestNormalized parentId(UUID parentId) {
    
    
    
    
    this.parentId = parentId;
    return this;
  }

   /**
   * Reference to the ID of the parent of this log. A log has a parent when it&#39;s a subrequest used to retrieve the final answer.
   * @return parentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Reference to the ID of the parent of this log. A log has a parent when it's a subrequest used to retrieve the final answer.")

  public UUID getParentId() {
    return parentId;
  }


  public void setParentId(UUID parentId) {
    
    
    
    this.parentId = parentId;
  }


  public RequestNormalized payload(PulzeCompletionRequest payload) {
    
    
    
    
    this.payload = payload;
    return this;
  }

   /**
   * The payload sent with the request
   * @return payload
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The payload sent with the request")

  public PulzeCompletionRequest getPayload() {
    return payload;
  }


  public void setPayload(PulzeCompletionRequest payload) {
    
    
    
    this.payload = payload;
  }


  public RequestNormalized privacyLevel(PrivacyLevelEnum privacyLevel) {
    
    
    
    
    this.privacyLevel = privacyLevel;
    return this;
  }

   /**
   * How much is logged? 1: everything, 2: mask request+response (but show log), 3: Not visible, not retrievable, no information stored.
   * @return privacyLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "_1", value = "How much is logged? 1: everything, 2: mask request+response (but show log), 3: Not visible, not retrievable, no information stored.")

  public PrivacyLevelEnum getPrivacyLevel() {
    return privacyLevel;
  }


  public void setPrivacyLevel(PrivacyLevelEnum privacyLevel) {
    
    
    
    this.privacyLevel = privacyLevel;
  }


  public RequestNormalized prompt(String prompt) {
    
    
    
    
    this.prompt = prompt;
    return this;
  }

   /**
   * The prompt in text format
   * @return prompt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The prompt in text format")

  public String getPrompt() {
    return prompt;
  }


  public void setPrompt(String prompt) {
    
    
    
    this.prompt = prompt;
  }


  public RequestNormalized promptTokens(Integer promptTokens) {
    
    
    
    
    this.promptTokens = promptTokens;
    return this;
  }

   /**
   * Number of tokens the request used
   * @return promptTokens
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Number of tokens the request used")

  public Integer getPromptTokens() {
    return promptTokens;
  }


  public void setPromptTokens(Integer promptTokens) {
    
    
    
    this.promptTokens = promptTokens;
  }


  public RequestNormalized promptTokensCost(Double promptTokensCost) {
    
    
    
    
    this.promptTokensCost = promptTokensCost;
    return this;
  }

  public RequestNormalized promptTokensCost(Integer promptTokensCost) {
    
    
    
    
    this.promptTokensCost = promptTokensCost.doubleValue();
    return this;
  }

   /**
   * Cost (in $) of the prompt
   * @return promptTokensCost
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Cost (in $) of the prompt")

  public Double getPromptTokensCost() {
    return promptTokensCost;
  }


  public void setPromptTokensCost(Double promptTokensCost) {
    
    
    
    this.promptTokensCost = promptTokensCost;
  }


  public RequestNormalized promptTokensCostSavings(Double promptTokensCostSavings) {
    
    
    
    
    this.promptTokensCostSavings = promptTokensCostSavings;
    return this;
  }

  public RequestNormalized promptTokensCostSavings(Integer promptTokensCostSavings) {
    
    
    
    
    this.promptTokensCostSavings = promptTokensCostSavings.doubleValue();
    return this;
  }

   /**
   * Cost (in $) saved in the prompt costs comparison to the benchmark model
   * @return promptTokensCostSavings
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Cost (in $) saved in the prompt costs comparison to the benchmark model")

  public Double getPromptTokensCostSavings() {
    return promptTokensCostSavings;
  }


  public void setPromptTokensCostSavings(Double promptTokensCostSavings) {
    
    
    
    this.promptTokensCostSavings = promptTokensCostSavings;
  }


  public RequestNormalized provider(String provider) {
    
    
    
    
    this.provider = provider;
    return this;
  }

   /**
   * The provider for the model.
   * @return provider
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The provider for the model.")

  public String getProvider() {
    return provider;
  }


  public void setProvider(String provider) {
    
    
    
    this.provider = provider;
  }


  public RequestNormalized requestType(RequestTypeEnum requestType) {
    
    
    
    
    this.requestType = requestType;
    return this;
  }

   /**
   * The type of request (text completion or chat) the user sends and expects back
   * @return requestType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The type of request (text completion or chat) the user sends and expects back")

  public RequestTypeEnum getRequestType() {
    return requestType;
  }


  public void setRequestType(RequestTypeEnum requestType) {
    
    
    
    this.requestType = requestType;
  }


  public RequestNormalized response(PulzeEngineResponse response) {
    
    
    
    
    this.response = response;
    return this;
  }

   /**
   * The response object
   * @return response
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The response object")

  public PulzeEngineResponse getResponse() {
    return response;
  }


  public void setResponse(PulzeEngineResponse response) {
    
    
    
    this.response = response;
  }


  public RequestNormalized responseText(String responseText) {
    
    
    
    
    this.responseText = responseText;
    return this;
  }

   /**
   * The response in text format
   * @return responseText
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The response in text format")

  public String getResponseText() {
    return responseText;
  }


  public void setResponseText(String responseText) {
    
    
    
    this.responseText = responseText;
  }


  public RequestNormalized statusCode(Integer statusCode) {
    
    
    
    
    this.statusCode = statusCode;
    return this;
  }

   /**
   * The status code of the request to the AI model
   * @return statusCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "-1", value = "The status code of the request to the AI model")

  public Integer getStatusCode() {
    return statusCode;
  }


  public void setStatusCode(Integer statusCode) {
    
    
    
    this.statusCode = statusCode;
  }


  public RequestNormalized timestamp(Integer timestamp) {
    
    
    
    
    this.timestamp = timestamp;
    return this;
  }

   /**
   * The timestamp of the request, in milliseconds
   * @return timestamp
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The timestamp of the request, in milliseconds")

  public Integer getTimestamp() {
    return timestamp;
  }


  public void setTimestamp(Integer timestamp) {
    
    
    
    this.timestamp = timestamp;
  }


  public RequestNormalized totalTokens(Integer totalTokens) {
    
    
    
    
    this.totalTokens = totalTokens;
    return this;
  }

   /**
   * Number of tokens of (request + response)
   * @return totalTokens
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Number of tokens of (request + response)")

  public Integer getTotalTokens() {
    return totalTokens;
  }


  public void setTotalTokens(Integer totalTokens) {
    
    
    
    this.totalTokens = totalTokens;
  }


  public RequestNormalized totalTokensCost(Double totalTokensCost) {
    
    
    
    
    this.totalTokensCost = totalTokensCost;
    return this;
  }

  public RequestNormalized totalTokensCost(Integer totalTokensCost) {
    
    
    
    
    this.totalTokensCost = totalTokensCost.doubleValue();
    return this;
  }

   /**
   * Cost (in $) of the (request + response)
   * @return totalTokensCost
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Cost (in $) of the (request + response)")

  public Double getTotalTokensCost() {
    return totalTokensCost;
  }


  public void setTotalTokensCost(Double totalTokensCost) {
    
    
    
    this.totalTokensCost = totalTokensCost;
  }


  public RequestNormalized totalTokensCostSavings(Double totalTokensCostSavings) {
    
    
    
    
    this.totalTokensCostSavings = totalTokensCostSavings;
    return this;
  }

  public RequestNormalized totalTokensCostSavings(Integer totalTokensCostSavings) {
    
    
    
    
    this.totalTokensCostSavings = totalTokensCostSavings.doubleValue();
    return this;
  }

   /**
   * Cost (in $) saved in total, in comparison to the benchmark model
   * @return totalTokensCostSavings
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Cost (in $) saved in total, in comparison to the benchmark model")

  public Double getTotalTokensCostSavings() {
    return totalTokensCostSavings;
  }


  public void setTotalTokensCostSavings(Double totalTokensCostSavings) {
    
    
    
    this.totalTokensCostSavings = totalTokensCostSavings;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the RequestNormalized instance itself
   */
  public RequestNormalized putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestNormalized requestNormalized = (RequestNormalized) o;
    return Objects.equals(this.appId, requestNormalized.appId) &&
        Objects.equals(this.at, requestNormalized.at) &&
        Objects.equals(this.children, requestNormalized.children) &&
        Objects.equals(this.completionTokens, requestNormalized.completionTokens) &&
        Objects.equals(this.completionTokensCost, requestNormalized.completionTokensCost) &&
        Objects.equals(this.completionTokensCostSavings, requestNormalized.completionTokensCostSavings) &&
        Objects.equals(this.costsIncurred, requestNormalized.costsIncurred) &&
        Objects.equals(this.created, requestNormalized.created) &&
        Objects.equals(this.feedback, requestNormalized.feedback) &&
        Objects.equals(this.goodAnswer, requestNormalized.goodAnswer) &&
        Objects.equals(this.id, requestNormalized.id) &&
        Objects.equals(this.latency, requestNormalized.latency) &&
        Objects.equals(this.model, requestNormalized.model) &&
        Objects.equals(this.modelId, requestNormalized.modelId) &&
        Objects.equals(this.namespace, requestNormalized.namespace) &&
        Objects.equals(this.owner, requestNormalized.owner) &&
        Objects.equals(this.parent, requestNormalized.parent) &&
        Objects.equals(this.parentId, requestNormalized.parentId) &&
        Objects.equals(this.payload, requestNormalized.payload) &&
        Objects.equals(this.privacyLevel, requestNormalized.privacyLevel) &&
        Objects.equals(this.prompt, requestNormalized.prompt) &&
        Objects.equals(this.promptTokens, requestNormalized.promptTokens) &&
        Objects.equals(this.promptTokensCost, requestNormalized.promptTokensCost) &&
        Objects.equals(this.promptTokensCostSavings, requestNormalized.promptTokensCostSavings) &&
        Objects.equals(this.provider, requestNormalized.provider) &&
        Objects.equals(this.requestType, requestNormalized.requestType) &&
        Objects.equals(this.response, requestNormalized.response) &&
        Objects.equals(this.responseText, requestNormalized.responseText) &&
        Objects.equals(this.statusCode, requestNormalized.statusCode) &&
        Objects.equals(this.timestamp, requestNormalized.timestamp) &&
        Objects.equals(this.totalTokens, requestNormalized.totalTokens) &&
        Objects.equals(this.totalTokensCost, requestNormalized.totalTokensCost) &&
        Objects.equals(this.totalTokensCostSavings, requestNormalized.totalTokensCostSavings)&&
        Objects.equals(this.additionalProperties, requestNormalized.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appId, at, children, completionTokens, completionTokensCost, completionTokensCostSavings, costsIncurred, created, feedback, goodAnswer, id, latency, model, modelId, namespace, owner, parent, parentId, payload, privacyLevel, prompt, promptTokens, promptTokensCost, promptTokensCostSavings, provider, requestType, response, responseText, statusCode, timestamp, totalTokens, totalTokensCost, totalTokensCostSavings, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestNormalized {\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    at: ").append(toIndentedString(at)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("    completionTokens: ").append(toIndentedString(completionTokens)).append("\n");
    sb.append("    completionTokensCost: ").append(toIndentedString(completionTokensCost)).append("\n");
    sb.append("    completionTokensCostSavings: ").append(toIndentedString(completionTokensCostSavings)).append("\n");
    sb.append("    costsIncurred: ").append(toIndentedString(costsIncurred)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    feedback: ").append(toIndentedString(feedback)).append("\n");
    sb.append("    goodAnswer: ").append(toIndentedString(goodAnswer)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    latency: ").append(toIndentedString(latency)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    modelId: ").append(toIndentedString(modelId)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("    privacyLevel: ").append(toIndentedString(privacyLevel)).append("\n");
    sb.append("    prompt: ").append(toIndentedString(prompt)).append("\n");
    sb.append("    promptTokens: ").append(toIndentedString(promptTokens)).append("\n");
    sb.append("    promptTokensCost: ").append(toIndentedString(promptTokensCost)).append("\n");
    sb.append("    promptTokensCostSavings: ").append(toIndentedString(promptTokensCostSavings)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    requestType: ").append(toIndentedString(requestType)).append("\n");
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    responseText: ").append(toIndentedString(responseText)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    totalTokens: ").append(toIndentedString(totalTokens)).append("\n");
    sb.append("    totalTokensCost: ").append(toIndentedString(totalTokensCost)).append("\n");
    sb.append("    totalTokensCostSavings: ").append(toIndentedString(totalTokensCostSavings)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("app_id");
    openapiFields.add("at");
    openapiFields.add("children");
    openapiFields.add("completion_tokens");
    openapiFields.add("completion_tokens_cost");
    openapiFields.add("completion_tokens_cost_savings");
    openapiFields.add("costs_incurred");
    openapiFields.add("created");
    openapiFields.add("feedback");
    openapiFields.add("good_answer");
    openapiFields.add("id");
    openapiFields.add("latency");
    openapiFields.add("model");
    openapiFields.add("model_id");
    openapiFields.add("namespace");
    openapiFields.add("owner");
    openapiFields.add("parent");
    openapiFields.add("parent_id");
    openapiFields.add("payload");
    openapiFields.add("privacy_level");
    openapiFields.add("prompt");
    openapiFields.add("prompt_tokens");
    openapiFields.add("prompt_tokens_cost");
    openapiFields.add("prompt_tokens_cost_savings");
    openapiFields.add("provider");
    openapiFields.add("request_type");
    openapiFields.add("response");
    openapiFields.add("response_text");
    openapiFields.add("status_code");
    openapiFields.add("timestamp");
    openapiFields.add("total_tokens");
    openapiFields.add("total_tokens_cost");
    openapiFields.add("total_tokens_cost_savings");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("completion_tokens");
    openapiRequiredFields.add("completion_tokens_cost");
    openapiRequiredFields.add("completion_tokens_cost_savings");
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("model");
    openapiRequiredFields.add("model_id");
    openapiRequiredFields.add("prompt_tokens");
    openapiRequiredFields.add("prompt_tokens_cost");
    openapiRequiredFields.add("prompt_tokens_cost_savings");
    openapiRequiredFields.add("response");
    openapiRequiredFields.add("timestamp");
    openapiRequiredFields.add("total_tokens");
    openapiRequiredFields.add("total_tokens_cost");
    openapiRequiredFields.add("total_tokens_cost_savings");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to RequestNormalized
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!RequestNormalized.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RequestNormalized is not found in the empty JSON string", RequestNormalized.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RequestNormalized.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("app_id") != null && !jsonObj.get("app_id").isJsonNull()) && !jsonObj.get("app_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `app_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("app_id").toString()));
      }
      if ((jsonObj.get("at") != null && !jsonObj.get("at").isJsonNull()) && !jsonObj.get("at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("at").toString()));
      }
      if (jsonObj.get("children") != null && !jsonObj.get("children").isJsonNull()) {
        JsonArray jsonArraychildren = jsonObj.getAsJsonArray("children");
        if (jsonArraychildren != null) {
          // ensure the json data is an array
          if (!jsonObj.get("children").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `children` to be an array in the JSON string but got `%s`", jsonObj.get("children").toString()));
          }

          // validate the optional field `children` (array)
          for (int i = 0; i < jsonArraychildren.size(); i++) {
            RequestInDBBase.validateJsonObject(jsonArraychildren.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("feedback") != null && !jsonObj.get("feedback").isJsonNull()) && !jsonObj.get("feedback").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `feedback` to be a primitive type in the JSON string but got `%s`", jsonObj.get("feedback").toString()));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("model").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `model` to be a primitive type in the JSON string but got `%s`", jsonObj.get("model").toString()));
      }
      if (!jsonObj.get("model_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `model_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("model_id").toString()));
      }
      if ((jsonObj.get("namespace") != null && !jsonObj.get("namespace").isJsonNull()) && !jsonObj.get("namespace").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `namespace` to be a primitive type in the JSON string but got `%s`", jsonObj.get("namespace").toString()));
      }
      if ((jsonObj.get("owner") != null && !jsonObj.get("owner").isJsonNull()) && !jsonObj.get("owner").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `owner` to be a primitive type in the JSON string but got `%s`", jsonObj.get("owner").toString()));
      }
      // validate the optional field `parent`
      if (jsonObj.get("parent") != null && !jsonObj.get("parent").isJsonNull()) {
        RequestInDBBase.validateJsonObject(jsonObj.getAsJsonObject("parent"));
      }
      if ((jsonObj.get("parent_id") != null && !jsonObj.get("parent_id").isJsonNull()) && !jsonObj.get("parent_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `parent_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("parent_id").toString()));
      }
      // validate the optional field `payload`
      if (jsonObj.get("payload") != null && !jsonObj.get("payload").isJsonNull()) {
        PulzeCompletionRequest.validateJsonObject(jsonObj.getAsJsonObject("payload"));
      }
      if ((jsonObj.get("prompt") != null && !jsonObj.get("prompt").isJsonNull()) && !jsonObj.get("prompt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `prompt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("prompt").toString()));
      }
      if ((jsonObj.get("provider") != null && !jsonObj.get("provider").isJsonNull()) && !jsonObj.get("provider").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `provider` to be a primitive type in the JSON string but got `%s`", jsonObj.get("provider").toString()));
      }
      if ((jsonObj.get("request_type") != null && !jsonObj.get("request_type").isJsonNull()) && !jsonObj.get("request_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `request_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("request_type").toString()));
      }
      // validate the required field `response`
      PulzeEngineResponse.validateJsonObject(jsonObj.getAsJsonObject("response"));
      if ((jsonObj.get("response_text") != null && !jsonObj.get("response_text").isJsonNull()) && !jsonObj.get("response_text").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `response_text` to be a primitive type in the JSON string but got `%s`", jsonObj.get("response_text").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RequestNormalized.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RequestNormalized' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RequestNormalized> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RequestNormalized.class));

       return (TypeAdapter<T>) new TypeAdapter<RequestNormalized>() {
           @Override
           public void write(JsonWriter out, RequestNormalized value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public RequestNormalized read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             RequestNormalized instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RequestNormalized given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RequestNormalized
  * @throws IOException if the JSON string is invalid with respect to RequestNormalized
  */
  public static RequestNormalized fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RequestNormalized.class);
  }

 /**
  * Convert an instance of RequestNormalized to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

