/*
 * Pulze.ai API
 * At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.AppUpdate;
import com.konfigthis.client.model.AppWithModelUpdatesInfo;
import com.konfigthis.client.model.LLMModelPolicies;
import com.konfigthis.client.model.LLMModelWeights;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppsApi
 */
@Disabled
public class AppsApiTest {

    private static AppsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new AppsApi(apiClient);
    }

    /**
     * Get App For Api Key
     *
     * Retrieves the App for the given API key.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAppForApiKeyTest() throws ApiException {
        AppWithModelUpdatesInfo response = api.getAppForApiKey()
                .execute();
        // TODO: test validations
    }

    /**
     * Update App And Models
     *
     * Update an App&#39;s properties: description, weights and policies.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePropertiesTest() throws ApiException {
        String description = null;
        UUID id = null;
        LLMModelPolicies policies = null;
        LLMModelWeights weights = null;
        UUID promptId = null;
        AppWithModelUpdatesInfo response = api.updateProperties(description, id, policies, weights)
                .promptId(promptId)
                .execute();
        // TODO: test validations
    }

}
